### PR TITLE
Rewrite to use new Lua completion API

### PR DESCRIPTION
**Pull request by Olical**
The new Conjure implementation is quite a bit simpler since it all takes place within the Neovim thread. I've just hooked directly into the Lua functions, seems to work great! Interested in hearing your feedback, feel free to change the code entirely, just wanted to get it working and show you how it worked first.

I've published this version to `coc-conjure-olical` as a temporary way to try it out too.

This will _only_ work against the develop branch of Conjure which will be going to master after I've finished the documentation and everyone's happy with the initial feature set. Maybe this could go to a develop branch or just not be published until the rewrite is all done and fully released?

### CODE REVIEW

**Comment by jlesquembre** [comment]
Nice! I'm following your work on Conjure, and it looks great. I didn't have time to test the new Conjure, but I continue to use the previous one. I was planning on updating `coc-conjure` at some point, but you were faster :) . I'm a bit busy right now. Hopefully next week I'll find some time, but definitely I'll try it and merge it. 
It also makes sense to me to merge it in a dev branch and wait to publish it until you are done with the rewrite.
Thanks once again for all your work on Conjure :)

**Comment by Olical** [comment]
I've simplified it a little more, you now don't need to worry about the intermediate promise waiting step.

**Comment by Olical** [comment]
Rewrote it a little so it no long relies on `completions-sync` which blocked Neovim a little bit. Now I use node's event loop and a little snooze promise (snooze since it's not a proper `sleep()` that blocks the process).

It's completely async now and should never block Neovim :tada:

Published at `coc-conjure-olical@0.3.3`

**Comment by jlesquembre** [comment]
I was testing the new version today and looks really good. I merged your changes in the `new-conjure` branch and published a beta release, `0.2.3-beta.0`. Once you release conjure, I'll merge into master and make a new npm release

**Comment by Olical** [comment]
Awesome work! Thank you so much!

**Pull request merged**
