### PR TITLE
Use conjure#completions (it's new) and some JS style

### PR DESCRIPTION
**Pull request by Olical**
So the second commit is entirely optional, I just aligned the JS with my editor warning which are based on https://standardjs.com/

If you just want the first commit that's totally fine, I'd recommend swapping that `let` to `const` and `==` to `===` at the very least though. Even if you want to keep the double quotes and semi-colons :slightly_smiling_face:

### CODE REVIEW

**Comment by Olical** [comment]
Looks like my completions don't trigger when I type `ui/` for example, but they do if I backspace the `/` and type it a couple of times :thinking: maybe that's something configurable with CoC. I haven't used it until today though so I'm not sure :sweat_smile:

**Comment by Olical** [comment]
`triggerCharacters: ['.', '/', '-']` might help... maybe...

**Comment by jlesquembre** [comment]
Thanks for the PR, I'm merging it but doing 2 changes:
- For formatting I let [prettier](https://prettier.io/) make decisions for me. I was using ALE fixers, but I recently switched to [CoC Prettier](https://github.com/neoclide/coc-prettier) since it seems faster
- In the readme, I'm removing the `Plug 'jlesquembre/coc-conjure'` part, it is not necessary, since CoC is managing JS extensions itself. Extensions are installed at `~/.config/coc/extensions`
I'm releasing a new version on NPM, you can update with `:CocUpdate` command

I'll investigate the issue about completions not triggering for `ui/`. If some extra configuration is required for CoC, I'll update the readme

**Comment by Olical** [comment]
That's totally fine, I should've kept the original style, sorry about that!

Oh, so I don't install it like a plugin? It's an npm package!? Oops... Shows how much I know about CoC. I'll set it up properly.

I do wonder if the lag in some completions is just it taking too long to respond or something.

What do you think about a callback based async system?

**Comment by jlesquembre** [comment]
Don't worry about the format, I just need to save the file and it's automatically re-formatted. I appreciate you PR.

About the CoC plugins, I'm neither an expert, but as far as I know, most of them are installed as npm packages, but CoC it's taking care of it. I think there are some exception and some CoC extensions are installed as usually with `Plug`

I like the idea about the async callback system, but I still don't know how to implement it. I'll try to find some time to research it. It's probably the best solution, if it can be implemented.

**Comment by Olical** [comment]
I'll mention it on https://github.com/Olical/conjure/issues/16 once I have an async completions hook, shouldn't be too hard. I think you give it a string for the function you want it to call. Then it'll execute it over RPC with the completions as the only argument.

**Comment by Olical** [comment]
Hmm, okay, possibly a horrible idea, but what if instead of a function callback, it would return a path to a temp file. You can read that file to get the results... just not sure how I have the reader block until the writer (conjure) is done. Maybe if the file is open for reading and you attempt to read until EOF you won't get an EOF until Conjure closes it :thinking: requires a little experimentation but could be a good way to do it!

Essentially what I'm proposing is using a file as a pipe, you read from it, I write to it. I'd write VimL data structures, or maybe Lua since that might be faster to parse.

**Comment by jlesquembre** [comment]
Yes, I'm not sure anymore if the solution with the callback can work currently with neovim. 
Why not just use a socket instead of the temp file? Maybe I'm missing something, but I think you can achieve the same and the temp file seems too hacky to me.

**Comment by Olical** [comment]
Yeah, definitely going to just select a port which you can ask for then
probably just JSON request / response for completions. Was thinking of
making it generic RPC so you could call anything in conjure but I think a
specialised completion port makes sense for now.

I'll let you know when that exists 😊 I've just been thinking about if for
a few days first. I agree, a file was a bad idea. Just didn't want to hunt
for open ports but it's okay.

**Pull request merged**
